const STATIC_MAIN_LAYOUT = 'MAIN'
const STATIC_PUBLIC_LAYOYT = 'PUBLIC'

const CREATE = 'CREATE'
const UPDATE = 'UPDATE'

const NAME_APPLICATION = "C.P. VIỆT NAM WEBSITE"
const VERSION_APP = "Version 1.00"
const COPYRIGHT_NOTICE =  "©2025 AXONS Corporate. All rights reserved"

export {
  STATIC_MAIN_LAYOUT,
  STATIC_PUBLIC_LAYOYT,
  CREATE,
  UPDATE,
  NAME_APPLICATION,
  VERSION_APP,
  COPYRIGHT_NOTICE
}